### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Xu-LongLi** [Brickworks/Nucleus-Altitude-Control#3] opened 2021-05-09 10:36 UTC
Hi，I am a student. When I run "configure_simulation.m" , there will be an error that the function or variable "setup_nctoolbox" cannot be recognized. How can I solve it?

**Comment by philiplinden** [comment] 2021-05-09 21:57
Hey I forgot to update the readme about this, sorry about that. I just pushed a few updates to the readme that should hopefully help.

This error occurs because [NCToolbox](https://github.com/nctoolbox/nctoolbox) is assumed to be next to this repo directory, see [Line 70](https://github.com/Brickworks/Nucleus-Altitude-Control/blob/5790e2dd52e82a73a405739b4a2b1b81c491e05a/configure_simulation.m#L70).

NCToolbox is an open source Matlab library that parses the "grib" files that you get when you [query GFS for weather data](https://www.nco.ncep.noaa.gov/pmb/products/gfs/). This is only required if you wish to model the balloon's flight path through "actual" atmosphere rather than the US Standard Atmosphere, 1976.

If you wish to place NCToolbox elsewhere on your machine, just change the path on Line 70 so that it still gets added to your Matlab Path.

Using the standard atmosphere is (now) on by default. To query weather data from GFS, set `use_std_atmo=false` ([Line 73](https://github.com/Brickworks/Nucleus-Altitude-Control/blob/5790e2dd52e82a73a405739b4a2b1b81c491e05a/configure_simulation.m#L73)) and [set up an initial location and start time](https://github.com/Brickworks/Nucleus-Altitude-Control/blob/5790e2dd52e82a73a405739b4a2b1b81c491e05a/configure_simulation.m#L75-80) on the next few lines.

Note that the modeled flight path doesn't match what [HabHub](http://predict.habhub.org/) predicts, so there might be something wrong. I am not sure where the issue is, but I suspect it comes from the lateral motion (lat/lon propagation). 

Let me know if this solves your issue!

**Comment by Xu-LongLi** [comment] 2021-05-12 10:37
Thank you for your help, I am sorry to reply to your message now. I have been writing my articles these days. The program has been able to run, thank you very much for your help. I am an aerospace major. I have been doing aerodynamic research, but my teacher now wants me to do control research, and I have encountered great difficulties. I am going to do a research on station-keeping of stratospheric aerostats based on wind field utilization. Have you done similar research? thank you for your help.

**Comment by philiplinden** [comment] 2021-05-12 20:00
Interesting! I have not done research in this field but I've collected some resources that might help you:

### Balloons

- **[Brickworks Nucleus Homepage](https://brickworks.github.io/Nucleus/) (aka this model).** This site and mission are still a work in progress, but we'll update it as time goes on. The approach here is a simple payload that drops ballast mass and opens a vent at the balloon to regulate altitude. A naive way to do it, but we're hoping to extend the duration of the flight by a couple of hours. The control system here is based on a PID with gain switching (the PID gains change depending on a flight control mode). 
- **[Stanford ValBal](http://asl.stanford.edu/wp-content/papercite-data/pdf/Suskho.Tedjarati.ea.AERO2017.pdf)**. Stanford's undergraduate group successfully flew a similar ballast/vent approach. They use a different kind of control algorithm  based on "incentives" (see section 4) but it's basically doing the same thing. The [ValBal source code is on github](https://github.com/stanford-ssi/balloons-VALBAL/blob/master/src/Controller.cpp).
- **[Loon](https://patents.google.com/patent/US20140048646/en)**. Google's Loon project used superpressure balloons, where the balloon is a constant volume and buoyancy is managed by controlling a bladder inside. This method is better than venting and dropping mass because it can pretty much be done indefinitely. Superpressure balloons are probably closest to aerostats. One thing you might find interesting: with Loon, they "steered" the balloons by changing altitude to ride wind currents that were flowing in the direction they wanted to go -- to change direction, they changed altitude to ride a different current.

### Controls

- **[Ardupilot](https://ardupilot.org/ardupilot/)**. One stop shop for flight control and mission planning with remote-operated aircraft. Handles all the flight control for you once you set it up. Definitely worth checking out -- best of all, it's open source.
- **[Steve Brunton Tutorials](https://www.youtube.com/c/Eigensteve/playlists)**. These tutorials are fantastic. Worth looking into as you explore different methods of controls.
- **[Kalman Filters for Non-Experts](https://simondlevy.academic.wlu.edu/kalman-tutorial/)**. Not directly relevant but very helpful for understanding Kalman Filters if you come across them.

I'm going to close this ticket but feel free to DM me on Twitter if you want to keep chatting about flight controls and balloons! https://twitter.com/PhilipJLinden

**Closed as completed by philiplinden** 2021-05-12 20:00 UTC
